#!/bin/sh
set -e

echo "Setting up iptables"

iptables -t nat -A POSTROUTING -j MASQUERADE

echo "Waiting for pipework to give us the eth1 interface"

pipework --wait

dnsmasq --interface=eth1 \
	--dhcp-range=192.168.242.2,192.168.242.99,255.255.255.0,1h \
	--dhcp-boot=pxelinux.0,pxeserver,192.168.242.1 \
	--pxe-service=x86PC,"Install Linux",pxelinux \
	--enable-tftp --tftp-root=/srv/tftp/ --no-daemon


